name: New Plugin Repo
description: You developed and want to submit your plugin to the directory
title: Requesting repo for <plugin.name>
assignees:
  - shchvova
body:
  - type: markdown
    attributes:
      value: |
        Filling out this issue would create a request to add a plugin to the plugin directory using automated system for publishing updates
  - type: textarea
    id: description
    attributes:
      label: plugin description
      placeholder: Describe your plugin in few words here
    validations:
      required: true
  - type: input
    id: publisherId
    attributes:
      label: Publisher ID
      description: Plugin's `publisherId` field used in build.settings
      placeholder: com.solar2d
    validations:
      required: true
  - type: input
    id: pluginName
    attributes:
      label: Plugin name
      description: Your plugin name. Typically what you pass to `require("...")` call
      placeholder: plugin.name
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and conditions
      description: Making sure we are on the same page
      options:
        - label: If I receive invitation to the new repo I will read the README, follow instructions and would not abuse the automation
          required: true
