name: New Plugin Repo
description: You developed a plugin and want to submit it to the directory
title: |
  Plugin repo request: ...
assignees:
  - shchvova
body:
  - type: textarea
    id: description
    attributes:
      label: plugin description
      placeholder: Describe your plugin in few words here
    validations:
      required: true
  - type: input
    id: publisherId
    attributes:
      label: `publisherId`
      description: Plugin's `publisherId` field used in build.settings
      placeholder: com.solar2d
    validations:
      required: true
  - type: input
    id: pluginName
    attributes:
      label: `plugin.name`
      description: Your plugin name. Typically what you pass to `require("...")` call
      placeholder: plugin.name
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and conditions
      description: Makins sure we are on the same page
      options:
        - label: When I receive invitation to the new repo I will read the README, would follow instructions and would not abuse the plugin publishing automation
          required: true
