on:
  workflow_dispatch:

jobs:
  update-issue-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Process plugin
        run: ./update_all.py --plugins-dir plugins
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./generate.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Auto-updating ${{ github.event.client_payload.repo }}"
          add: "plugins docs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
